#!/bin/sh

# i/o scheduler
echo noop > /sys/block/sdb/queue/scheduler

# I/O queue
echo 1024 > /sys/block/sdb/queue/nr_requests

# read-ahead
hdparm -a 2048 /dev/sdb

# sleep for first HDD drive
hdparm -Y /dev/sda

# create users cache folders
mount /var/tmp
cd /home/;
for i in *
do
	mkdir -p /var/tmp/$i/cache
	chown $i /var/tmp/$i
done
