#!/bin/sh

# i/o scheduler
echo deadline > /sys/block/sdb/queue/scheduler

# I/O queue
echo 1024 > /sys/block/sdb/queue/nr_requests

# fix iscsi by increasing timeouts in aggressive real-world network environment
echo 900 > /sys/block/sdb/device/timeout

# fix hung tasks waiting for I/O op on device
echo 0 > /proc/sys/kernel/hung_task_timeout_secs

# read-ahead
hdparm -a 4096 /dev/sdb

# sleep for first HDD drive
hdparm -Y /dev/sda

# create users cache folders
mount /var/tmp
cd /home/;
for i in *
do
	mkdir -p /var/tmp/$i/cache
	chown $i -R /var/tmp/$i
done
