#!/bin/bash
ISO=$1

if [ "$ISO" = "" ]
then
	echo "Usage: ubi <path to ISO file>"
	exit 1
fi

cd /sys/block

for i in sd*
do
	r=$(cat $i/removable)
	#echo $r
	if [ "$r" -eq "1" ]
	then
		#echo $i $r
	
		vendor=$(cat /sys/block/sdb/device/vendor)
		model=$(cat /sys/block/sdb/device/model)

		echo -n "Drive [/dev/$i] is removable [$vendor $model], confirm? [Y]: "
		read x
		if [ "$x" = "Y" ]
		then
			echo OK
			umount /dev/${i}1 >/dev/null 2>&1
			dd if=/dev/zero of=/dev/$i bs=1M count=1
			parted /dev/$i -s "mklabel msdos"
			parted /dev/$i -a opt -s "mkpart pri fat32 0% 100%"
			parted /dev/$i -s "set 1 boot on"
			mkfs.vfat /dev/${i}1
			mkdir /tmp/ubi >/dev/null 2>&1
			mount /dev/${i}1 /tmp/ubi
			unetbootin \
				method=diskimage \
				isofile=$ISO \
				installtype=USB \
				targetdrive=/dev/${i}1 \
				autoinstall=yes
			umount /tmp/ubi >/dev/null 2>&1
			rmdir /tmp/ubi
			sync
			echo DONE
			exit 0
		fi
	fi
done
