---
- name: apt update
  apt: update_cache=yes

- name: apt clean
  shell: apt clean all

- name: restart ssh
  service: name=ssh state=restarted

- name: restart cpufrequtils
  service: name=cpufrequtils state=restarted

- name: exec rc-local
  shell: /etc/rc.local

- name: update sysctl
  shell: /sbin/sysctl -p

- name: remount-all
  shell: mount -o remount -a

- name: clean-apt-cache-remount
  shell: bash -c '/bin/rm -f /var/cache/apt/archives/*; mount /var/cache/apt/archives'

- name: home-cache-mount
  shell: bash -c 'mount /var/tmp; cd /home/; for i in *; do mkdir /var/tmp/$i; [ -d $i/.cache ] && mv $i/.cache /var/tmp/$i/cache; ln -sf /var/tmp/$i/cache $i/.cache; chown $i -R /var/tmp/$i; done'
  ignore_errors: true

- name: rm-resolv
  file: state=absent path=/etc/resolv.conf

- name: restart network-manager
  service: state=restarted name=network-manager

- name: apt upgrade
  apt: update_cache=yes upgrade=full force=yes allow_unauthenticated=yes

- name: grub
  shell: update-grub2

- name: restart cupsbrowsed
  service: state=restarted name=cups-browsed

- name: restart avahi
  service: state=restarted name=avahi-daemon