---
- name: create bareos-repo configuration
  copy: >
    src=bareos.list dest=/etc/apt/sources.list.d/bareos.list
    owner=root group=root mode=0644

- name: check bareos-client version
  apt: name=bareos-client state=latest cache_valid_time=86400 force=yes install_recommends=yes update_cache=yes
