---
- name: Install CPU freq tools
  apt: pkg=cpufrequtils state=installed

- name: default file for CPU freq
  lineinfile: path=/etc/default/cpufrequtils state=present regexp='^GOVERNOR' line='GOVERNOR="performance"' create=yes
  notify: restart cpufrequtils

- name: set CPU freq to max
  replace: dest=/etc/default/cpufrequtils regexp='^GOVERNOR=\"powersave\"' replace='GOVERNOR="performance"'
  notify: restart cpufrequtils

- name: disable CPU ondemand
  service: name=ondemand enabled=no
