- name: tail resolver
  lineinfile: dest=/etc/resolvconf/resolv.conf.d/tail create=yes state=present line="nameserver 172.16.5.1"

- name: APT sources
  copy: >
    src=sources.list dest=/etc/apt/sources.list owner=root group=root mode=0644
  notify: apt update

- name: apt HTTPs?
  apt: pkg=apt-transport-https state=latest cache_valid_time=86400 force=yes install_recommends=yes update_cache=yes

- name: kernel headers
  apt: pkg=linux-headers-4.4.0-31 state=present cache_valid_time=86400 force=yes install_recommends=yes update_cache=yes

- name: kernel extra
  apt: pkg=linux-image-extra-4.4.0-31-generic state=present cache_valid_time=86400 force=yes install_recommends=yes update_cache=yes

- name: kernel audio
  apt: pkg=linux-sound-base state=present cache_valid_time=86400 force=yes install_recommends=yes update_cache=yes

- name: rc.local
  copy: >
    src=rc.local dest=/etc/rc.local owner=root group=root mode=0755

- name: >
    src=tune-ssd dest=/usr/local/sbin/tune-ssd owner=root group=root mode=0755
  notify: exec rc-local
