- name: tail resolver
  lineinfile: dest=/etc/resolvconf/resolv.conf.d/tail create=yes state=present line="nameserver 172.16.5.1"

- name: APT sources
  copy: >
    src=sources.list dest=/etc/apt/sources.list owner=root group=root mode=0644
  notify: apt update

- name: apt HTTPs?
  apt: pkg=apt-transport-https state=latest cache_valid_time=86400 force=yes install_recommends=yes update_cache=yes

- name: kernel headers
  apt: pkg=linux-headers-4.13.0-30-lowlatency state=present cache_valid_time=86400 force=yes install_recommends=yes update_cache=yes

- name: kernel extra
  apt: pkg=linux-image-4.13.0-30-lowlatency state=present cache_valid_time=86400 force=yes install_recommends=yes update_cache=yes

- name: kernel audio
  apt: pkg=linux-sound-base state=present cache_valid_time=86400 force=yes install_recommends=yes update_cache=yes

- name: rc.local
  copy: >
    src=rc.local dest=/etc/rc.local owner=root group=root mode=0755

- name: tune-ssd script
  copy: >
    src=tune-ssd dest=/usr/local/sbin/tune-ssd owner=root group=root mode=0755
  notify: exec rc-local

- name: force caching to RAM dirty_ratio to 99 perc
  lineinfile: dest=/etc/sysctl.conf create=yes state=present line="vm.dirty_ratio = 99"
  notify: update sysctl

- name: force caching to RAM dirty_background_ratio 50 perc
  lineinfile: dest=/etc/sysctl.conf create=yes state=present line="vm.dirty_background_ratio = 50"
  notify: update sysctl

- name: force caching to RAM dirty_expire_centisecs to 30min write delay
  lineinfile: dest=/etc/sysctl.conf create=yes state=present line="vm.dirty_expire_centisecs = 1800"
  notify: update sysctl

- name: force caching to RAM dirty_writeback_centisecs to 30min write delay
  lineinfile: dest=/etc/sysctl.conf create=yes state=present line="vm.dirty_writeback_centisecs = 1800"
  notify: update sysctl
