---
- name: check if printer configured
  tags: printer
  shell: "lpstat -d | grep Kyocera"
  register: printer_check
  ignore_errors: yes
  # changed_when: false

- name: remove all existing printers
  tags: printer
  when: printer_check.stdout == ""
  shell: lpstat -s|awk '/:/{print $3}'|awk -F':' '{print "lpadmin -x "$1}'|sh

- name: configure Kyocera MFP
  tags: printer
  when: printer_check.stdout == ""
  ignore_errors: yes
  shell: /usr/sbin/lpadmin -p Kyocera_ECOSYS_M2735dw -D Kyocera_ECOSYS_M2735dw -L Work -E -v ipp://Kyocera%20ECOSYS%20M2735dw._ipp._tcp.local/
  
- name: configure Kyocera MFP as default
  tags: printer
  when: printer_check.stdout == ""
  ignore_errors: yes
  shell: lpadmin -d Kyocera_ECOSYS_M2735dw

- name: disable cups auto-addint network printers
  tags: printer
  when: printer_check.stdout == ""
  service: name=cups-browsed state=restarted enabled=true
  notify: restart cupsbrowsed
  ignore_errors: yes

- name: disable printer autodiscover via cups browsed
  tags: printer
  replace: dest=/etc/cups/cups-browsed.conf regexp='^# BrowseProtocols none' replace='BrowseProtocols none'
  notify: restart cupsbrowsed
  ignore_errors: yes

- name: disable printer autodiscover via avahi
  tags: printer
  replace: dest=/etc/avahi/avahi-daemon.conf regexp='^#enable-dbus=yes' replace='enable-dbus=no'
  notify: restart avahi
  ignore_errors: yes


