---
- name: check if printer configured
  tags: printer
  shell: "lpstat -d 2>&1 | grep Kyocera"
  register: printer_check
  ignore_errors: yes
  #changed_when: false

- debug:
    var: printer_check

- name: disable cups auto-addint network printers
  service: name=cups-browsed state=stopped enabled=false
  ignore_errors: yes

- name: remove all existing printers
  tags: printer
  when: printer_check is failed
  shell: lpstat -s|awk '/:/{print $3}'|awk -F':' '{print "lpadmin -x "$1}'|sh

- name: configure Kyocera MFP
  tags: printer
  when: printer_check is failed
  ignore_errors: yes
  shell: /usr/sbin/lpadmin -p Kyocera_ECOSYS_M2735dw -D Kyocera_ECOSYS_M2735dw -L Lab -E -v ipp://Kyocera%20ECOSYS%20M2735dw._ipp._tcp.local/
  
- name: configure Kyocera MFP as default
  tags: printer
  when: printer_check is failed
  ignore_errors: yes
  shell: lpadmin -d Kyocera_ECOSYS_M2735dw