---
# Printer HP setup
- name: check if HP printer configured
  tags: hp
  shell: /bin/bash -c "/usr/bin/hp-probe -bcups 2>&1 | grep 172.16.5.20"
  register: hp_check
  ignore_errors: yes
  changed_when: false

- name: need to configure HP printer
  ignore_errors: yes
  when: hp_check is failed
  tags: hp
  expect:
     command: /bin/bash -c "/usr/bin/hp-setup -i -a -x 172.16.5.20"
     responses:
       download: d
       license: y

- name: update HP plugin
  tags: hp
  ignore_errors: yes
  expect:
     command: /bin/bash -c "/usr/bin/hp-plugin -i"
     responses:
       d=download: y
       license: y
       Please enter 'd': d
