---
- name: check if printer configured
  tags: printer
  shell: "lpstat -l -p Kyocera_ECOSYS_M2735dw | grep Kyocera_ECOSYS_M2735dw.ppd"
  register: printer_check
  ignore_errors: yes

- name: remove all existing printers
  tags: printer
  when: printer_check.stdout == ""
  shell: lpstat -s|awk '/:/{print $3}'|awk -F':' '{print "lpadmin -x "$1}'|sh

- name: kyocera sane package copy
  tags: printer
  copy: >
    src=kyocera-sane_2.0.1923_amd64.deb dest=/tmp/kyocera-sane_2.0.1923_amd64.deb owner=root group=root mode=0644

- name: kyocera sane package install
  tags: printer
  shell: dpkg -i /tmp/kyocera-sane_2.0.1923_amd64.deb

- name: kyocera driver package copy
  tags: printer
  copy: >
    src=kyodialog_9.0-0_amd64.deb dest=/tmp/kyodialog_9.0-0_amd64.deb owner=root group=root mode=0644

- name: kyocera driver package install
  tags: printer
  shell: dpkg -i /tmp/kyodialog_9.0-0_amd64.deb

- name: configure Kyocera MFP
  tags: printer
  when: printer_check.stdout == ""
  ignore_errors: yes
  shell: /usr/sbin/lpadmin -p Kyocera_ECOSYS_M2735dw -D Kyocera_ECOSYS_M2735dw -L Work -E -v socket://172.16.5.21 -P /usr/share/ppd/kyocera/Kyocera_ECOSYS_M2735dw.ppd
  
- name: configure Kyocera MFP as default
  tags: printer
  when: printer_check.stdout == ""
  ignore_errors: yes
  shell: lpadmin -d Kyocera_ECOSYS_M2735dw

- name: disable cups auto-addint network printers
  tags: printer
  when: printer_check.stdout == ""
  service: name=cups-browsed state=restarted enabled=true
  notify: restart cupsbrowsed
  ignore_errors: yes

- name: disable printer autodiscover via cups browsed
  tags: printer
  replace: dest=/etc/cups/cups-browsed.conf regexp='^# BrowseProtocols none' replace='BrowseProtocols none'
  notify: restart cupsbrowsed
  ignore_errors: yes

- name: disable printer autodiscover via avahi
  tags: printer
  replace: dest=/etc/avahi/avahi-daemon.conf regexp='^#enable-dbus=yes' replace='enable-dbus=no'
  notify: restart avahi
  ignore_errors: yes


