---
- name: check openssl version
  apt: name=openssl state=latest cache_valid_time=86400 force=yes install_recommends=yes update_cache=yes

- name: install unattended-upgrades
  apt: pkg=unattended-upgrades state=latest cache_valid_time=86400 force=yes install_recommends=yes update_cache=yes

- name: create APT auto-upgrades configuration
  copy: >
    src=auto-upgrades dest=/etc/apt/apt.conf.d/20auto-upgrades
    owner=root group=root mode=0644

- name: install update-notifier-common
  apt: pkg=update-notifier-common state=present
  ignore_errors: true

- name: install fail2ban
  apt: pkg=fail2ban state=present
  ignore_errors: true

- name: fail2ban ssh enable with custom conf file
  copy: >
          src=fail2ban.local dest=/etc/fail2ban/jail.d/defaults-debian.conf
          owner=root group=root mode=0644
  notify: restart fail2ban

- name: timezone to Europe/Vilnius
  file: src=/usr/share/zoneinfo/Europe/Vilnius dest=/etc/localtime state=link

- name: correct fstab
  replace: dest=/etc/fstab regexp='^\/dev\/mapper\/client\-rootfs' replace='/dev/sdb'

- name: fstab-opt1
  tags: fstab
  lineinfile: dest=/etc/fstab regexp='\/var\/cache\/apt\/archives' line='tmpfs /var/cache/apt/archives tmpfs defaults,noexec,nosuid,nodev 0 0' state=present
  notify: clean-apt-cache-remount

- name: fstab-opt2
  tags: fstab
  lineinfile: dest=/etc/fstab regexp='^tmpfs /tmp' line='tmpfs /tmp tmpfs defaults,noatime,nodiratime,mode=1777,noexec,nosuid,nodev,size=10% 0 0' state=present
  notify: remount-all

- name: fstab-opt3
  tags: fstab
  lineinfile: dest=/etc/fstab regexp='^tmpfs /var/log' line='tmpfs /var/log tmpfs defaults,noatime,nodiratime,mode=1777,noexec,nosuid,nodev,size=10% 0 0' state=present
  notify: remount-all

- name: fstab-opt4
  tags: fstab
  lineinfile: dest=/etc/fstab regexp='^tmpfs /var/tmp' line='tmpfs /var/tmp tmpfs defaults,noatime,nodiratime,mode=1777,noexec,nosuid,nodev,size=30% 0 0' state=present
  notify: home-cache-mount

- name: fstab options
  tags: fstab
  include: fstab-opts.yml point=/ opts=discard,errors=remount-ro,noatime,nodiratime,commit=600
  notify: remount-all

- name: rsyslog remote
  tags: syslog
  lineinfile: dest=/etc/rsyslog.d/90-remote.conf
              regexp='^'
              line='auth.*,authpriv.*,kern.*,cron.*,*.=warn,*.=emerg,*.=alert,*.=crit,*.=err,*.=error,*.=warn   @172.16.5.254'
              state=present
              create=True
  notify: restart rsyslog

- name: remove default syslog file
  tags: syslog
  file: path="/etc/rsyslog.d/50-default.conf" state=absent
  notify: restart rsyslog

- name: comment out deprecated KLogPermitNonKernelFacility 
  tags: syslog
  replace: dest=/etc/rsyslog.conf
           regexp='^\$KLogPermitNonKernelFacility'
           replace='#$KLogPermitNonKernelFacility'
  notify: restart rsyslog

- name: clean man-db daily tasks
  file: path=/etc/cron.daily/man-db state=absent

- name: clean man-db weekly tasks
  file: path=/etc/cron.weekly/man-db state=absent

- name: check chrome dir
  file: path=/etc/chromium-browser state=directory

- name: disable chromium disk cache
  lineinfile: dest=/etc/chromium-browser/default regexp='^CHROMIUM_FLAGS=""' line='CHROMIUM_FLAGS="--disk-cache-dir=/dev/null --disk-cache-size=1"' state=present

- name: diable firefox disk cache
  copy: >
          src=syspref.js dest=/etc/firefox/syspref.js
          owner=root group=root mode=0644
