---
- name: check openssl version
  apt: name=openssl state=latest cache_valid_time=86400 force=yes install_recommends=yes update_cache=yes

- name: install unattended-upgrades
  apt: pkg=unattended-upgrades state=latest cache_valid_time=86400 force=yes install_recommends=yes update_cache=yes

- name: create APT auto-upgrades configuration
  copy: >
    src=auto-upgrades dest=/etc/apt/apt.conf.d/20auto-upgrades
    owner=root group=root mode=0644

- name: install update-notifier-common
  apt: pkg=update-notifier-common state=present
  ignore_errors: true

- name: timezone to Europe/Vilnius
  file: src=/usr/share/zoneinfo/Europe/Vilnius dest=/etc/localtime state=link

- name: correct fstab
  replace: dest=/etc/fstab regexp='^\/dev\/mapper\/client\-rootfs' replace='/dev/sdb'

- name: fstab-opt1
  tags: fstab
  lineinfile: dest=/etc/fstab regexp='\/var\/cache\/apt\/archives' line='tmpfs /var/cache/apt/archives tmpfs defaults,noexec,nosuid,nodev 0 0' state=present
  notify: clean-apt-cache-remount

- name: fstab-opt2
  tags: fstab
  lineinfile: dest=/etc/fstab regexp='^tmpfs /tmp' line='tmpfs /tmp tmpfs defaults,noatime,nodiratime,mode=1777,noexec,nosuid,nodev,size=10% 0 0' state=present
  notify: remount-all

- name: fstab-opt3
  tags: fstab
  lineinfile: dest=/etc/fstab regexp='^tmpfs /var/log' line='tmpfs /var/log tmpfs defaults,noatime,nodiratime,mode=1777,noexec,nosuid,nodev,size=10% 0 0' state=present
  notify: remount-all

- name: fstab-opt4
  tags: fstab
  lineinfile: dest=/etc/fstab regexp='^tmpfs /var/tmp' line='tmpfs /var/tmp tmpfs defaults,noatime,nodiratime,mode=1777,noexec,nosuid,nodev,size=30% 0 0' state=present
  notify: home-cache-mount

- name: fstab options
  tags: fstab
  include: fstab-opts.yml point=/ opts=discard,errors=remount-ro,noatime,nodiratime,commit=600
  notify: remount-all

- name: clean man-db daily tasks
  file: path=/etc/cron.daily/man-db state=absent

- name: clean man-db weekly tasks
  file: path=/etc/cron.weekly/man-db state=absent

- name: check browsers default conf dir
  file: path={{ item }} state=directory
  with_items:
    - /etc/chromium-browser
    - /etc/firefox

- name: disable chromium disk cache
  copy: >
    src=chrome.default dest=/etc/chromium-browser/default owner=root group=root mode=0644

- name: diable firefox disk cache
  copy: >
          src=syspref.js dest=/etc/firefox/syspref.js owner=root group=root mode=0644

# Configure autolock with slock
- name: check dir
  file: path=/usr/share/mate/autostart state=directory

- name: slock autostart
  copy: >
    src=autolock.desktop dest=/usr/share/mate/autostart/autolock.desktop
    owner=root group=root mode=0755

- name: dconf keyboard layouts
  dconf:
    key: "/org/mate/desktop/peripherals/keyboard/kbd/layouts"
    value: "['us', 'ru']"

- name: dconf keyboard layout change
  dconf:
    key: "/org/mate/desktop/peripherals/keyboard/kbd/options"
    value: "['grp_led\tgrp_led:scroll', 'grp\tgrp:ctrl_shift_toggle']"
