---
# BGPview
- name: bgpview
  copy: >
    src=bgpview dest=/usr/local/bin/bgpview
    owner=root group=root mode=0755

# Firefox
- name: repo for firefox
  apt_repository: repo={{ item }} state=present
  with_items:
    - ppa:ubuntu-mozilla-daily/ppa
    - ppa:mozillateam/firefox-next
    - ppa:ubuntu-mozilla-daily/firefox-aurora
    - ppa:ubuntu-mozilla-security/ppa
  ignore_errors: yes

# syncthing repos
- name: syncthing key
  apt_key:
    url: https://syncthing.net/release-key.txt
    state: present
  ignore_errors: yes

- name: syncthing repo
  apt_repository:
    repo: deb https://apt.syncthing.net/ syncthing stable
    state: present
  notify: apt update
  ignore_errors: yes

# Mate
- name: add repo for mate - xenial
  apt_repository: repo='ppa:ubuntu-mate-dev/xenial-mate' state=present
  notify: apt update
  ignore_errors: yes

# Mass install
- name: install soft
  apt:
    name:
      - sudo
      - open-iscsi
      - mtr
      - traceroute
      - dnsutils
      - atop
      - xarchiver
      - rar
      - simple-scan
      - firefox
      - firefox-locale-ru
      - thunderbird
      - thunderbird-locale-ru
      - chromium-browser
      - gxkb
      - rdesktop
      - language-pack-en
      - language-pack-ru
      - xournal
      - qpdf
      - pulseaudio
      - libreoffice
      - xsane # for HP printer scan mode
      - python-ptyprocess # for HP
      - python-pexpect # for HP printer config (next)
      - snmp-mibs-downloader # for HP printer
      - xss-lock # to lock the screen
      - suckless-tools
      - libnet-telnet-cisco-perl # for bgpview
      - telegraf # monitoring & metrics
      - xprintidle
      - initramfs-tools
      - busybox
      - keepassx # password management
      - skypeforlinux
      - smartmontools
      - lm-sensors
      - localepurge
    state: present
    force: yes
    install_recommends: yes
    cache_valid_time: 86400
    autoclean: yes
  ignore_errors: yes


# Mass install for hosts not 'dt'
- name: install soft
  apt:
    name:
      - mate-desktop
      - remmina
      - sddm
      - sddm-theme-breeze
    state: latest
    force: yes
    install_recommends: yes
    cache_valid_time: 86400
    autoclean: yes
  ignore_errors: yes

# SNAP install
- name: snap install
  snap:
    name:
      - chromium
      - telegram-desktop

#- name: install unetbootin
#  apt: name=unetbootin state=latest force=yes install_recommends=yes cache_valid_time=86400
#  ignore_errors: yes

# UBI script
#- name: ubi | unetbootin
#  copy: >
#    src=ubi dest=/usr/local/bin/ubi
#    owner=root group=root mode=0755
# =========== CUSTOM ===============

# mail autoconfiguration for thunderbird
- name: thunderbird autoconfig for ISP
  copy: >
    src=dcxv.com.xml dest=/usr/lib/thunderbird/isp/dcxv.com.xml
    owner=root group=root mode=0644

#
- name: specs
  copy: >
    src=specs dest=/usr/local/bin/specs
    owner=root group=root mode=0755

# RealVNC client from official website
- name: realvnc download
  get_url: url="https://www.realvnc.com/download/file/viewer.files/VNC-Viewer-6.17.1113-Linux-x64.deb" dest="/var/cache/apt/archives/realvnc.deb"
  ignore_errors: yes

- name: realvnc install
  apt: deb="/var/cache/apt/archives/realvnc.deb" state=present 

# telegraf metrics config
- name: telegraf config download
  get_url: url="https://172.16.5.15/telegraf.conf" dest="/etc/telegraf/telegraf.conf" validate_certs=no
  ignore_errors: yes

- name: telegraf chown
  file: dest=/etc/telegraf owner=telegraf group=telegraf mode=0755 recurse=yes
  ignore_errors: yes

- name: xidle load
  get_url: url="https://172.16.5.15/xidle" dest="/usr/bin/xidle" validate_certs=no owner=root group=root mode=0755
  ignore_errors: yes

- name: telegraf sudoers
  copy:
    dest: "/etc/sudoers.d/telegraf"
    content: |
      telegraf ALL=(ALL) NOPASSWD:/usr/sbin/smartctl
      telegraf ALL=(ALL) NOPASSWD:/usr/sbin/nvme
      telegraf ALL=(ALL) NOPASSWD:/usr/sbin/hddtemp
      telegraf ALL=(ALL) NOPASSWD:/usr/bin/xprintidle

- name: telegraf restart
  service: name=telegraf state=restarted
  ignore_errors: yes

# REMOVE repos
- name: remove old repos
  file: path={{ item }} state=absent
  with_items:
    - /etc/apt/sources.list.d/nightly_apt_ring_cx_ubuntu_16_04.list
    - /etc/apt/sources.list.d/deb_opera_com_opera_stable.list
    - /etc/apt/sources.list.d/opera-stable.list


# REMOVE soft
- name: remove unneded soft
  apt:
    state: absent
    name: 
      - at
      - lvm2
      - arpwatch
      - rsyslog
      - eject
      - man-db
      - manpages
      - libreoffice-help-ru
      - libreoffice-help-en-us
      - dropbear
      - dropbear-initramfs
      - ubuntu-touch-sounds
      - network-manager-pptp
      - pptp-linux
      - element-desktop
      - telegram-desktop
      - hplip

- name: sddm directory
  file: path=/etc/sddm.conf.d state=directory mode=0755

- name: sddm config file
  copy: >
    src=uid.conf dest=/etc/sddm.conf.d/uid.conf owner=root group=root mode=0644

- name: sddm default display manager
  copy: >
    src=default-display-manager dest=/etc/X11/default-display-manager owner=root group=root mode=0644
