---

# Whois
- name: whois
  apt: name=whois state=latest force=yes install_recommends=yes

# MTR
- name: mtr
  apt: name=mtr state=latest force=yes install_recommends=yes

# DIG
- name: dig_install
  apt: name=dnsutils state=latest force=yes install_recommends=yes

# Atop
- name: atop
  apt: name=atop state=latest force=yes install_recommends=yes

# Mplayer
- name: mplayer
  apt: name=mplayer state=latest force=yes install_recommends=yes

# Scan
- name: simple scan
  apt: name=simple-scan state=latest force=yes install_recommends=yes

# Firefox
- name: repo for firefox
  apt_repository: repo='ppa:ubuntu-mozilla-daily/ppa' state=present
  notify: apt update

- name: repo for firefox security
  apt_repository: repo='ppa:ubuntu-mozilla-security/ppa' state=present
  notify: apt update

- name: install/update Firefox
  apt: name=firefox state=latest force=yes install_recommends=yes

- name: Firefox locale RU
  apt: name=firefox-locale-ru state=latest force=yes install_recommends=yes

- name: install/update Thunderbird
  apt: name=thunderbird state=latest cache_valid_time=86400 force=yes install_recommends=yes

- name: Thunderbird locale RU
  apt: name=thunderbird-locale-ru state=latest cache_valid_time=86400 force=yes install_recommends=yes

# Opera
- name: key for opera repo
  apt_key: url=https://deb.opera.com/archive.key state=present
  ignore_errors: yes

- name: repo for opera
  apt_repository: repo='deb https://deb.opera.com/opera-stable/ stable non-free' state=present
  notify: apt update

- name: install/update Opera
  apt: name=opera-stable state=latest cache_valid_time=86400 force=yes install_recommends=yes

- name: install/update Chromium
  apt: name=chromium-browser state=latest cache_valid_time=86400 force=yes install_recommends=yes

# Java
- name: java jre
  tags: java
  apt: name=default-jre state=latest cache_valid_time=86400 force=yes install_recommends=yes
  async: 900
  poll: 10

- name: java jdk
  tags: java
  apt: name=default-jdk state=latest cache_valid_time=86400 force=yes install_recommends=yes
  async: 900
  poll: 10

- name: IceD tea
  tags: java
  apt: name=icedtea-8-plugin state=latest cache_valid_time=86400 force=yes install_recommends=yes

- name: set licence selected
  tags: java
  shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

- name: set licence seen
  tags: java
  shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 seen true | /usr/bin/debconf-set-selections

- name: oracle java repo
  tags: java
  apt_repository: repo='ppa:webupd8team/java' state=present
  notify: apt update

- name: oracle java 8
  tags: java
  apt: name=oracle-java8-installer state=latest cache_valid_time=86400 force=yes install_recommends=yes

- name: oracle java 8 set default
  tags: java
  apt: name=oracle-java8-set-default state=latest cache_valid_time=86400 force=yes install_recommends=yes

- name: java 8 security file
  tags: java
  copy: >
    src=java.security dest=/etc/java-8-oracle/security/java.security
    owner=root group=root mode=0644

- name: java icedtea security file
  tags: java
  copy: >
    src=java.security dest=/etc/java-8-openjdk/security/java.security
    owner=root group=root mode=0644

- name: java exceptions whitelist
  tags: java
  shell: >
    awk -F\: '/home/{if ($3>999) {print $6}}' /etc/passwd
  changed_when: false
  register: user_home

- name: java make execption directory
  tags: java
  file: path={{user_home.stdout}}/.java/deployment/security/ state=directory mode=0775 recurse=yes

- name: exception copy to home
  tags: java
  copy: >
    src=exception.sites dest={{user_home.stdout}}/.java/deployment/security/exception.sites
    owner=root group=root mode=0644

- name: kvm script
  tags: java
  copy: >
    src=kvm dest=/usr/local/bin/kvm
    owner=root group=root mode=0755

# RealVNC client from official website
- name: realvnc download
  get_url: url="https://www.realvnc.com/download/file/viewer.files/VNC-Viewer-6.17.1113-Linux-x64.deb" dest="/var/cache/apt/archives/realvnc.deb"
  ignore_errors: yes

- name: realvnc install
  apt: deb="/var/cache/apt/archives/realvnc.deb" state=present 

# Jabber
- name: install/update pidgin
  apt: name=pidgin state=latest cache_valid_time=86400 force=yes install_recommends=yes

- name: install/update pidgin otr
  apt: name=pidgin-otr state=latest cache_valid_time=86400 force=yes install_recommends=yes

- name: install/update psi+
  apt: name=psi-plus state=latest cache_valid_time=86400 force=yes install_recommends=yes
  when: ansible_fqdn != "dt"

- name: install Pulseaudio
  apt: name=pulseaudio state=latest cache_valid_time=86400 force=yes install_recommends=yes

# LibreOffice
- name: install LibreOffice
  apt: name=libreoffice state=latest cache_valid_time=86400 force=yes install_recommends=yes

# Skype
- name: skype repo
  apt_repository: repo='deb [arch=amd64] https://repo.skype.com/deb stable main' state=present
  notify: apt update

- name: skype repo sign
  apt_key: url=https://repo.skype.com/data/SKYPE-GPG-KEY state=present
  notify: apt update
  ignore_errors: yes

- name: install Skype
  apt: name=skypeforlinux state=latest cache_valid_time=86400 force=yes install_recommends=yes

# Mate
- name: add repo for mate
  apt_repository: repo='ppa:ubuntu-mate-dev/xenial-mate' state=present
  notify: apt update
  when: ansible_fqdn != "dt"

# Mate install
- name: mate core install
  apt: name=ubuntu-mate-core state=latest cache_valid_time=86400 force=yes install_recommends=yes
  when: ansible_fqdn != "dt"

- name: mate desktop install
  apt: name=ubuntu-mate-desktop state=latest cache_valid_time=86400 force=yes install_recommends=yes
  when: ansible_fqdn != "dt"

# RDP tools
- name: remmina install
  apt: name=remmina state=latest cache_valid_time=86400 force=yes install_recommends=yes
  when: ansible_fqdn != "dt"

- name: rdp
  apt: name=rdesktop state=latest cache_valid_time=86400 force=yes install_recommends=yes

# Languages
- name: lang pack en
  apt: name=language-pack-en state=latest cache_valid_time=86400 force=yes install_recommends=yes

- name: lang pack ru
  apt: name=language-pack-ru state=latest cache_valid_time=86400 force=yes install_recommends=yes

# PDF
- name: pdf xournal
  apt: name=xournal state=latest cache_valid_time=86400 force=yes install_recommends=yes

- name: qpdf
  apt: name=qpdf state=latest cache_valid_time=86400 force=yes install_recommends=yes

# Gobby
- name: gobby
  apt: name=gobby state=latest cache_valid_time=86400 force=yes install_recommends=yes

# VLC
- name: vlc
  apt: name=vlc state=latest cache_valid_time=86400 force=yes install_recommends=yes

# Printer HP setup
- name: printer HP tools
  apt: name=hplip state=latest cache_valid_time=86400 force=yes install_recommends=yes

- name: install expect module
  apt: name=python-pexpect state=latest cache_valid_time=86400 force=yes install_recommends=yes

- name: check if HP printer configured
  tags: hp
  shell: /bin/bash -c "/usr/bin/hp-probe -bcups 2>&1 | grep 172.16.5.20"
  register: hp_check
  ignore_errors: yes
  changed_when: false

- name: need to configure HP printer
  when: hp_check|failed
  tags: hp
  expect:
     command: /bin/bash -c "/usr/bin/hp-setup -i -a -x 172.16.5.20"
     responses:
       download: d
       license: y

# Ring
- name: key for ring
  apt_key:
    keyserver: pgp.mit.edu
    id: A295D773307D25A33AE72F2F64CD5FA175348F84
  ignore_errors: yes

- name: repo for ring
  apt_repository: repo='deb http://nightly.apt.ring.cx/ubuntu_16.04/ ring main' state=present
  notify: apt update
  ignore_errors: yes

- name: ring
  apt: name=ring state=latest force=yes install_recommends=yes
  ignore_errors: yes

- name: keyboard switch
  apt: name=gxkb state=latest force=yes install_recommends=yes
  ignore_errors: yes
